name: Node.js CI

on:
  push:
    branches: [master, workflow]
  pull_request:
    branches: [master, workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Start server
        run: npm start & sleep 15
      - name: Run tests
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        run: npm test
